DROP TABLE AWARD IF EXISTS;
 
CREATE TABLE AWARD  (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    YEAR VARCHAR(4),
    TITLE VARCHAR(100),
    STUDIOS VARCHAR(100),
    PRODUCERS VARCHAR(200),
    WINNER VARCHAR(100)

) ;

